services:

  opensearch:
    image: opensearchproject/opensearch:3
    container_name: local-opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
      - POSTGRES_DB=rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: local-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
      until curl -s http://ollama:11434 >/dev/null; do sleep 2; done;
      OLLAMA_HOST=http://ollama:11434 ollama pull qwen3:4b;
      OLLAMA_HOST=http://ollama:11434 ollama pull qwen3-embedding:0.6b;
      "

  app:
    build: .
    container_name: rag-app
    depends_on:
      - opensearch
      - ollama-init
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
      - OPENSEARCH_BASE_URL=http://opensearch:9200
      - OPENSEARCH_INDEX_NAME=rag_documents
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rag_db
      - SPRING_DATASOURCE_USERNAME=rag_user
      - SPRING_DATASOURCE_PASSWORD=rag_password

volumes:
  opensearch-data:
  ollama-data:
  pgvector-data: